backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

logo_url: https://previews.dropbox.com/p/thumb/AAcKHAQBGiCtaaVn5hdhcgWVmecRUTJbfP2Ra8nvv0IZO80V1uQkIz-s6-1r1IgV8mEDHUHrKnXxY9ePcQYuFnX6Pl9zo6ROWB6GQCwrZnauQ7k00lx-8FVdPiFmRHl9qIigOu2hlDbDql5biVdGQOtybNbBpCBVPgSwHI7BrbizKtz7suH4-X1-iPwqU8cL7oqVBGtNKL_KxCmFOiKDdf9XvUpLvqdVvCZfyHFXHwu1Py0EsUFJwhRhQ8CMbaj7JZSMfHqVb9tIZRpsQegsNlrieM7oL0Bgx3Tvub8LD0Iki1U9EsfTLgSKkvOclNvmLJroeeD0tjiEiBfKlA2Q5cZIM1eDaxpHDXOnYeQSVT_J-JLOQrZlmHD4xh8RRi0Tqt8kiapFk8A7HnysY9Nsc5SCZEfkPmiY4aPVrEm5eQXU-uaE6VcJVIitiuZ7Y89Qta_3G3aSe6o84AbUX-Xnjy1E/p.png?fv_content=true&size_mode=5

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "blog-post"}
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "description", label: "Description",  widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown", required: true }
      - { name: "author", label: "Author", widget: "relation", collection: "author", searchFields: ["name"], valueField: "name", multiple: false, required: true }
      - { name: "categories", label: "Categories", widget: "relation", collection: "category", searchFields: ["title"], valueField: "title", multiple: true, required: true }
      - { name: "featureImage", label: "Feature Image", widget: "image", required: true }
      - { name: "path", label: "Path", widget: "string", required: true }
      - { name: "date", label: "Date", widget: date, required: true }
      - { name: "featured",label: "Featured", widget: "boolean", default: false, required: false}
      - name: "metadata"
        label: "Metadata"
        widget: "object" 
        fields: 
        - { name: seoTitle, label: SEO Title, widget: "string", required: true }
        - { name: seoDescription, label: SEO Description, widget: "text", required: true }
        - { name: seoImage, label: SEO Image, widget: "image", required: true }
        - { name: seoKeywords, label: SEO Keywords, widget: "string", required: true }

  - name: category
    label: Category
    folder: content/category
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "category"}
      - { name: title, label: Title, required: true }
      - { name: "sidebar",label: "Sidebar Display", widget: "boolean", default: false, required: false}
      - name: "metadata"
        label: "Metadata"
        widget: "object" 
        required: false
        fields: 
        - { name: seoTitle, label: SEO Title, widget: "string", required: true }
        - { name: seoDescription, label: SEO Description, widget: "text", required: true }
        - { name: seoImage, label: SEO Image, widget: "image", required: true }
        - { name: seoKeywords, label: SEO Keywords, widget: "string", required: true }

  - name: author
    label: Author
    folder: content/author
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "author"}
      - { name: name, label: Name, required: true }
      - { name: profileImage, label: Profile Image, widget: "image", required: true }
      - name: "metadata"
        label: "Metadata"
        widget: "object" 
        required: false
        fields: 
        - { name: seoTitle, label: SEO Title, widget: "string", required: true }
        - { name: seoDescription, label: SEO Description, widget: "text", required: true }
        - { name: seoImage, label: SEO Image, widget: "image", required: true }
        - { name: seoKeywords, label: SEO Keywords, widget: "string", required: true }
