backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "blog-post"}
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description",  widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "author", label: "Author", widget: "relation", collection: "author", searchFields: ["name"], valueField: "name", multiple: false }
      - { name: "category", label: "Category", widget: "relation", collection: "category", searchFields: ["title"], valueField: "title", multiple: true }
      - { name: "featureImage", label: "Feature Image", widget: "image" }
      - { name: "path", label: "Path", widget: "string" }
      - { name: "date", label: "Date", widget: date }
      - { name: "featured",label: "Featured", widget: "boolean", default: false}
      - name: "metadata"
        label: "Metadata"
        widget: "object" 
        required: "false"
        fields: 
        - { name: seoTitle, label: SEO Title, widget: "string" }
        - { name: seoDescription, label: SEO Description, widget: "text" }
        - { name: seoImage, label: SEO Image, widget: "image" }
        - { name: seoKeywords, label: SEO Keywords, widget: "string" }

  - name: category
    label: Category
    folder: content/category
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "category"}
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: "sidebar",label: "Sidebar Display", widget: "boolean", default: false}
      - name: "metadata"
        label: "Metadata"
        widget: "object" 
        required: "false"
        fields: 
        - { name: seoTitle, label: SEO Title, widget: "string" }
        - { name: seoDescription, label: SEO Description, widget: "text" }
        - { name: seoImage, label: SEO Image, widget: "image" }
        - { name: seoKeywords, label: SEO Keywords, widget: "string" }

  - name: author
    label: Author
    folder: content/author
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "author"}
      - { name: name, label: Name }
      - { name: profileImage, label: Profile Image, widget: "image" }
      - { name: path, label: Path }
      - name: "metadata"
        label: "Metadata"
        widget: "object" 
        required: "false"
        fields: 
        - { name: seoTitle, label: SEO Title, widget: "string" }
        - { name: seoDescription, label: SEO Description, widget: "text" }
        - { name: seoImage, label: SEO Image, widget: "image" }
        - { name: seoKeywords, label: SEO Keywords, widget: "string" }
